# Generated by Django 2.1.5 on 2019-01-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190130_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver',
            field=models.BooleanField(default=False),
        ),
    ]
