# Generated by Django 2.1.5 on 2019-01-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vechicleMake',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='vechiclePlate',
            field=models.CharField(default='', max_length=128),
        ),
    ]
